---
title: "LengthDist_AZKABANKrill"
author: "Muriel Dunn"
date: '2022-05-19'
output: html_document
---

---
title: "Fit length ditributions_Tromsøflaket"
author: "Muriel Dunn"
date:  "`r Sys.Date()`"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
library(fitdistrplus)
require(actuar)
require(gamlss.dist)
library(truncnorm)
```


## Fitting the distributions
I want to find the best fit for the length measurements I have from the multinet and tucker trawl data. A represenattive length distribution will inform and constrain the model input possibilities.

```{r values}

#Tucker Trawl @ KB3 Jan 15-16th
x_krill = c(7.14,7.14,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,8.73,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,9.52,10.32,10.32,10.32,10.32,10.32,10.32,10.32,10.32,10.32,10.32,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,11.11,12.70,12.70,12.70,12.70,12.70,12.70,12.70,12.70,12.70,12.70,13.49,13.49,13.49,14.29,14.29,17.46,19.05,19.05,21.43,22.22,23.81,25.40,26.19) #mm

```



## Krill

```{r}
krill_dist = fitdist(c(x_krill), "lnorm")
length(x_krill)
mean(x_krill)
sd(x_krill)
plot(krill_dist)
summary(krill_dist)
```

